create table if not exists application_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    uuid text unique primary key,
    username text unique,
    email text unique,
    password text,
    avatar text,
    lastname text,
    name text,
    middle_name text,
    birthday date,
    placed_at date,
    role text
);